variables:

- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
- name:  dockerRegisteryServiceConnection
  value: devops-class-acr-connection
- name: azsubscription
  value: devops-appsvc-rg
- name: web-app-name
  value: devops-course-web-app
- name: imageRepository
  value: devopsclassrepo
- name: containerRegistery
  value: devopsclasscontainer
- name: tag
  value: latest

jobs:

- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(tag)'
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 42698cb1-9984-4a92-bd85-1a03f44fdbc8
      repository: $(imageRepository)
      Dockerfile: devopswebapp/Dockerfile
      tags: $(tag)
  - task: AzureWebAppContainer@1
    displayName: deploying to web app
    inputs:
      azureSubscription: $(azsubscription)
      appName: $(web-app-name)
      containers: $(containerRegistery)/$(imageRepository):$(tag)
...
